language: php
sudo: required

install:
  - mkdir var
  - composer install

addons:
  sonarcloud:
    organization: ${SONAR_ORGANIZATION} # the key of the org you chose at step #3
    token:
      secure: ${SONAR_TOKEN}
    branches:
      - master
      
script:
  - ./bin/phpunit
  - sonar-scanner