language: php
php:
  - '7.1'
env:
  - APP_ENV="test"
  
sudo: required
services:
  - docker
env:
  - DOCKER_COMPOSE_VERSION=3.2
before_install:
  - docker-compose up -d

install:
  - mkdir var
  - docker exec -it file_consumer_php composer install

addons:
  sonarcloud:
    organization: ${SONAR_ORGANIZATION} # the key of the org you chose at step #3
    token:
      secure: ${SONAR_TOKEN}
    branches:
      - master
      
script:
  - docker exec -it file_consumer_php docker-php-ext-enable xdebug
  - docker-exec -it file_consumer_php ./bin/phunit --coverage-clover reports/php/report --log-junit reports/php/phpunit.coverage
  - sonar-scanner