language: php
php:
  - '7.1'
env:
  - APP_ENV="test"
  
sudo: required
services:
  - docker
env:
  - DOCKER_COMPOSE_VERSION=3.5
before_install:
  - rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - mv docker-compose /usr/local/bin
  - docker-compose up -d

install:
  - mkdir var
  - docker exec -it file_consumer_php composer install

addons:
  sonarcloud:
    organization: ${SONAR_ORGANIZATION} # the key of the org you chose at step #3
    token:
      secure: ${SONAR_TOKEN}
    branches:
      - master
      
script:
  - docker exec -it file_consumer_php docker-php-ext-enable xdebug
  - docker exec -it file_consumer_php ./bin/phpunit --coverage-clover reports/php/phpunit.coverage.xml --log-junit reports/php/logfile.xml
#  - sonar-scanner
