language: php
sudo: required
services:
  - docker
env:
  - DOCKER_COMPOSE_VERSION=3.2
before_install:
  - cd docker
  - docker-compose build --force-rm --no-cache
  - docker-compose up - d

install:
  - docker exec -d file_consumer_php mkdir var
  - docker exec -d file_consumer_php composer install --prefer-dist

script:
  - docker exec -it file_consumer_php vendor/bin/phpunit