version: '3.5'

services:
  php:
    environment:
      - APP_ENV=dev
      - KERNEL_CLASS=App\Kernel
    container_name: file_consumer_php
    image: fgamess/php7-stack-symfony
    volumes:
      - .:/var/www:cached
      - ./logs:/var/logs:cached
    networks:
      - app_network
      
networks:
  app_network:
    driver: bridge
volumes:
    logs:
