version: '3.2'

services:
  php:
    container_name: file_consumer_php
    image: fgamess/php7-stack-symfony
    volumes:
      - .:/var/www:cached
      - ./logs:/var/logs:cached
    ports:
      - 9000:80
    networks:
      - app_network
  nginx:
    container_name: file_consumer_nginx
    image: fgamess/nginx-for-symfony
    ports:
      - 14300:80
    volumes:
      - ./logs/nginx:/logs/nginx
    networks:
      - app_network
      
networks:
  app_network:
    driver: bridge
volumes:
    logs: