version: 2

machine:
  php:
    version: 7.1
jobs:
  build-and-unit-tests:
    docker:
      - image: circleci/php:latest-node-browsers
    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "composer.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: mkdir var
      - run: export APP_ENV="test"
      - run:
          name: Install project dependencies
          command: composer install -n --prefer-dist

      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}
      - run:
          name: Run Unit tests
          command: ./bin/phpunit tests/Unit
  build-and-functional-tests:
      - run:
          name: Run Functional tests
          command: ./bin/phpunit tests/Functional
          
workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-unit-tests
      - build-and-functional-tests:
          requires:
            - build-and-unit-tests