version: 2
jobs:
  build:
    docker:
      - image: circleci/php:latest-node-browsers
    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "composer.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: mkdir var

      - run:
          name: Install project dependencies
          command: composer install -n --prefer-dist

      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}
  unit_tests:
    docker:
      - image: circleci/php:latest-node-browsers
    steps: 
      - run:
        name: Run Unit tests
        command: vendor/bin/phpunit tests/Unit
  functional_tests:
    docker:
      - image: circleci/php:latest-node-browsers
    steps:
      - run:
        name: Run Functional tests
        command: vendor/bin/phpunit tests/Functional
          
workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - unit_tests:
          requires:
            - build
      - functional_tests:
          requires:
            - unit_tests