
workflows:
  version: 2
  jobs:
    build:
      docker:
        # specify the version you desire here
        - image: circleci/php:latest-node-browsers

        # Specify service dependencies here if necessary
        # CircleCI maintains a library of pre-built images
        # documented at https://circleci.com/docs/2.0/circleci-images/
        # - image: circleci/mysql:9.4

      working_directory: ~/repo

      steps:
        - checkout

        # Download and cache dependencies
        - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "composer.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
        - run: mkdir var

        - run:
          name: Install project dependencies
          command: composer install -n --prefer-dist

        - save_cache:
            paths:
              - ./vendor
            key: v1-dependencies-{{ checksum "composer.json" }}
    unit_tests:
      requires:
        - build
      steps: 
        - run:
          name: Run Unit tests
          command: vendor/bin/phpunit tests/Unit
    functional_tests:
      requires:
        - unit_tests
      steps:
        - run:
          name: Run Functional tests
          command: vendor/bin/phpunit tests/Functional